client.go
This is intended to allow implementation of hashicorp/terraform#13722.
cc @sean-
=> client: Allow InsecureSkipVerify to be set for TLS

machines.go
=> Merge PR for introducing boolean tags handling

images.go
This will need cherry-picking (or otherwise transferring) into the reorganization but solves a problem I have immediately without needing to refactor the entire API. cc @cheapRoc, @sean-
=> images: Add missing parameters to ListImage operation

network/fabrics.go
Yet another naming change. This simply continues removing the stutter in the Fabrics API that (apparently) I had already begun.
/cc @sean-
=> Finish removing stutter from network Fabrics API

compute/instances.go, compute/instances_test.go, examples/compute/create_instance.go
CNS was not respected when creating a new instance. This addresses that concern, adds a thorough acceptance test for instance creation, and includes an example for others.
=> instances: Patch CNS processing during instance creation

authentication/ssh_agent_signer.go
This commit adds support for keys in the form SHA256:fingerprint in addition to MD5:fingerprint and fingerprints with no additional information regarding their contents. This is useful since the Triton documentation suggests using `ssh-keygen -l -f ~/.ssh/id_rsa` which by default returns a SHA256 formatted fingerprint in newer versions of OpenSSH.
cc @cheapRoc @stack72 @misterbisson
=> authentication: Support SHA256 Key IDs

compute/instances.go
Easy one that came up in the Terraform provider.
Tracking at terraform-providers/terraform-provider-triton#37
=> Patch where Triton might return a null response

compute/instances.go
CloudAPI will soon support [affinity rules](https://apidocs.joyent.com/docker/features/placement#affinity-filter-syntax) similar to Docker API. In order to utilize this in other areas, specifically Terraform, I've included the base functionality here. It's a simple slice of strings.
/cc @stack72 @sean-
=> Introduce pre-release Affinity rules field for CreateMachine

storage/snaplink.go
Add Accept and Accept-Version HTTP Headers
Also fix the Location header to actually point to the correct item
=> Fix Snaplink

compute/client.go, compute/snapshots.go, compute/snapshots_test.go
This continues to build on #25
@cheapRoc
=> Add support for List, Get and Delete Snapshots

compute/snapshots.go, compute/snapshots_test.go
Add the missing endpoints for snapshot management
=> Add support for CreateSnapshot and StartMachineFromSnapshot endpoints

identity/users.go, identity/users_test.go
=> bug: CreateUser and UpdateUser should return User rather than no response

compute/client.go, network/firewall.go, network/firewall_test.go
=> Add support for ListRulesMachines Endpoint

storage/objects.go
This lets users submit HTTP Headers along with their object requests.
=> Add an optional input header attribute, Headers to Get, Put, and Delete.

storage/directory.go
`json.Decode()` can attempt to decode a short read. This would lead to strange list errors, like:
```
unable to list manta directory: Error decoding List response: invalid character ':' looking for beginning of value
```
Fortunately since the directory list operation returns newline-delimited JSON fragments, we can use a line-oriented scanner and unmarshal the desired entry reliably.
This PR assumes #68 has been applied.
=> Fix flaky list op

examples/storage/forceDelete.go, storage/directory.go
Fixes #60
When a client wants to delete a directory, but that directory has child objects in it, we can now add
a new parameter to `DeleteDirectoryInput` called `ForceDelete` - this is a bool that tells triton-go to
walk the tree and delete all of the children (directories or objects)
```
storage [manta-dir-force-delete●●] % ./forceDelete
2017/12/12 19:17:30 FULL PATH: /stack72_joyent/stor/level1
2017/12/12 19:17:31 Deleting folder path: /stack72_joyent/stor/level1/level2
2017/12/12 19:17:32 Deleting folder path: /stack72_joyent/stor/level1/level2/level3
2017/12/12 19:17:32 Deleting folder path: /stack72_joyent/stor/level1/level2/level3/level4
2017/12/12 19:17:33 Deleting folder path: /stack72_joyent/stor/level1/level2/level3/level4/level5
2017/12/12 19:17:34 Deleting folder path: …
```
=> storage/directory: Add support for ForceDelete

README.md, authentication/private_key_signer.go, authentication/ssh_agent_signer.go, client/client.go, client/client_test.go, examples/account/account_info.go, examples/account/config.go, examples/account/keys.go, examples/compute/create_instance.go, examples/compute/instances.go, examples/network/create_fabric.go, examples/storage/createjob.go, examples/storage/forceDelete.go, examples/storage/forcePut.go, examples/storage/getobject.go, examples/storage/mls.go, examples/storage/putobject.go, examples/storage/signUrl.go, testutils/runner.go, triton.go
Fixes: #67 
Fixes: #83 
Adds support for RBAC via the ability to pass a Username to the SSH Agent signers
The examples and the associated README has been updated accordingly
=> Add support for rbac

account/account.go, account/account_test.go, account/config.go, account/config_test.go, account/keys.go, account/keys_test.go, compute/datacenters.go, compute/images.go, compute/instances.go, compute/packages.go, compute/services.go, compute/snapshots.go, compute/snapshots_test.go, identity/roles.go, identity/users.go, identity/users_test.go, network/fabrics.go, network/firewall.go, network/firewall_test.go, network/network.go, storage/job.go, storage/signing.go
=> Migrate from fmt.Sprintf to path.Join in URL structures

examples/storage/list_directory/main.go, storage/directory.go, storage/job.go, storage/objects.go, storage/signing.go, storage/snaplink.go, storage/snaplink_test.go
Right now, I am not going to add tests for manta - they are proving to not be a pretty thing - I will come back and update these in the future
=> Remove errwrap from storage pkg

authentication/signature.go, compute/client.go, compute/volumes.go, compute/volumes_test.go, examples/compute/volumes/crud/main.go, examples/compute/volumes/list_volumes/main.go
This will allow the CRUD functionality of volumes when they are
enabled in each of the environments. Right now, it is a whitelist
feature only
=> compute/volumes: Add support for volume management in Triton

CHANGELOG.md, README.md, compute/instances.go, storage/directory.go
This commit fixes few small typos found while reading the project code.
=> Correct few typos found.

compute/instances.go, compute/instances_test.go
This commit adds a `Count` method which can be used to get a total
number of currently provisioned instances as a single integer value,
and does not retrieve any details of each of the instances.
This superceeds #113
=> Add support for getting a count of current instances from the CloudAPI.

compute/instances.go
For the upcoming TSG work, I want to be able to specify that names
start with a specific prefix, i.e. MyTSG-
Triton-go will append a random string to the name and pass that to
cloudapi
Please note: Name will always take priority over name-prefix
=> compute/instances: Add ability to support name-prefix

cmd/agent/storage/public.go, cmd/config/config.go, cmd/internal/config/public.go, cmd/manta/cmd/list/public.go, cmd/manta/cmd/root.go, cmd/manta/cmd/version/public.go, cmd/manta/main.go, cmd/triton/cmd/instances/create/public.go, cmd/triton/cmd/instances/delete/public.go, cmd/triton/cmd/instances/get/public.go, cmd/triton/cmd/instances/list/public.go
Adding the stub for a manta cli. This has basic list directory func
only
=> CLI: Manta

cmd/agent/compute/public.go, cmd/triton/cmd/instances/get/public.go, cmd/triton/cmd/instances/ip/public.go, cmd/triton/cmd/instances/public.go, cmd/triton/cmd/instances/reboot/public.go, cmd/triton/cmd/instances/start/public.go, cmd/triton/cmd/instances/stop/public.go
This adds support for Start, Stop, Reboot and IP
=> cli/instances: Add support for instance management

cmd/agent/compute/public.go, cmd/triton/cmd/datacenters/public.go, cmd/triton/cmd/root.go, cmd/triton/cmd/services/public.go
Adds support for:
% triton datacenters
% triton services
=> cli/compute-utils: Add support for compute datacenters and services

storage/directory.go, storage/directory_test.go, storage/snaplink_test.go
See #156 
Test plagiarized from `snaplink_test.go`
=> Directory listing marker fix

Gopkg.lock, compute/images_test.go, examples/storage/create_mpu/main.go, storage/objects.go
* Fixes #160, but omits listing multipart uploads
=> Add support for multipart upload (#160)

CHANGELOG.md, compute/volumes.go, compute/volumes_test.go, version.go
=> Add support for volume tags

CHANGELOG.md, Makefile, README.md, compute/datacenters_test.go, compute/images_test.go, compute/instances.go, compute/instances_test.go, compute/packages_test.go, go.mod, go.sum, network/network_test.go, testutils/runner.go, testutils/steps.go, version.go
This gets it working for me against my local DC.
=> Update compute acceptance tests to work with COAL

CHANGELOG.md, README.md, client/client.go, utils/http_debugging.go, version.go
Example:
```
$ TRITON_TRACE_HTTP=1 ./triton instance ls
REQUEST:
--
GET /jill/machines?offset=0 HTTP/1.1
Host: cloudapi.dingo.local
User-Agent: triton-go/1.8.0 (amd64-darwin; go1.12.5)
Accept: application/json
Accept-Version: 8
Authorization: Signature keyId="/jill/keys/de:e7:73:9a:b0:91:31:3e:72:8d:9f:62:ca:58:a2:ec",algorithm="rsa-sha1",headers="date",signature="ABCXYZl+=="
Date: Mon, 04 May 2020 18:56:12 UTC
Accept-Encoding: gzip
RESPONSE:
--
HTTP/1.1 200 OK
Content-Length: 1731
Access-Control-Allow-Headers: Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, Api-Version, Response-Time
Access-Control-Allow-Methods: POST, GET, HEAD
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Api-Version, Request-Id, Response-Time
Api-Version: 9.0.0
Connection: …
```
=> Add ability to trace CloudAPI HTTP requests (#180)

CHANGELOG.md, compute/instances.go, utils/http_debugging.go, version.go
FYI, I plan to integrate this into the v1 branch and then use this for terraform.
=> Add delegate_dataset support to instance creation

authentication/private_key_signer.go, authentication/ssh_agent_signer.go, authentication/util.go, go.mod, go.sum
=> added pkcs8 and edcsa for private_key_signer
