accounts.go
accounts_test.go
client.go
config.go
config_test.go
datacenters.go
datacenters_test.go
fabrics.go
firewall.go
images.go
images_test.go
keys.go
keys_test.go
machines.go
machines_test.go
networks.go
networks_test.go
packages.go
random_test.go
roles.go
runner_test.go
services.go
services_test.go
statebag_test.go
steps_test.go

This commit makes every method to every Triton client take a context in order that the consumer can set deadlines, timeouts and so forth. This also mandates the removal of the RetryableHTTP library in favour of the standard library HTTP client (without upstreaming changes to RetryableHTTP).
This is a breaking change, however it is a vast improvement and worth taking the hit sooner rather than later.
We also clean up various nits - format strings without formatting values and so forth.

breaking: Introduce client-wide context.Context

---

machines.go

This is required to detect that machines have in fact been fully removed when deleting an image by Packer.  Follow up PR to packer relying on this change required.

Always return the `StatusCode` when returning an error.

---

client.go

This PR addresses an edge case where a user can cause a self inflicted NPE ([here](https://github.com/joyent/triton-go/blob/master/client.go#L113) and [here](https://github.com/joyent/triton-go/blob/master/client.go#L176)) by not constructing a proper client without passing in an `authentication.Signer`. 
I've added a little more error handling and a new default behavior which utilizes `SSHAgentSigner` if an `SDC_KEY_ID` is found in the user's environment. Also, I believe this is how other HTTP clients act that I've used in the past.

Patch NPE by constructing a default SSHAgentSigner under NewClient

---

README.md
errors.go
machines.go

Expanded the scope of this PR to include:
* Added `GetNIC()` support
* improvements to both `AddNIC()`, and `RemoveNIC()`.
In `RemoveNIC()`: MAC addresses arg in `RemoveNIC()` can not include `:` between hex nibbles.  Strep them out before making the API call.  TL;DR: CloudAPI returns colon delimited nibbles, however `RemoveNIC()` does not permit colons when round-tripping the data.
Related docs: 
* https://apidocs.joyent.com/cloudapi/#RemoveNic
* https://apidocs.joyent.com/cloudapi/#GetNic
* https://apidocs.joyent.com/cloudapi/#AddNic

Improve machine *NIC() API

---

compute/datacenters.go
compute/datacenters_test.go
compute/instances.go
compute/instances_test.go

While integrating with Terraform I found a few bugs in naming around datacenters and instances.

Align a few API names for datacenters and instances

---

compute/instances.go
compute/instances_test.go

This PR cleans up a few features while patching a mistyped endpoint.
- Patch [an existing bug](https://github.com/joyent/triton-go/blob/master/compute/instances.go#L464) where the `UpdateMetadata` endpoint is misusing `/tags` instead of `/metadata`. 
- Complete the metadata API by introducing `GetMetadata`, `ListMetadata`, `DeleteMetadata`, and `DeleteAllMetadata`. 
- Introduce queries for the `ListInstances` endpoint.
Also, ref: #25

Complete Instances Metadata and ListInstances APIs

---

compute/errors.go

Paired with @jen20 to diagnose that the wrong error casting was being
done - therefore, compute.IsSpecificError was failing

error: Change from TritonError to client.ClientError

---

compute/errors.go

Reverting the change where TritonError was changed to client.ClientError
Discussed with @sean- and @cheapRoc

Backing out Error type change

---

account/account_test.go
account/config_test.go
account/keys_test.go
client/client.go
client/errors.go
compute/datacenters_test.go
compute/errors.go
compute/images.go
compute/images_test.go
compute/instances.go
compute/instances_test.go
compute/services_test.go
examples/account/account_info.go
network/networks_test.go
testutils/steps.go

The original bug stems from `client.DecodeError()` returning a `client.ClientError{}` not a `client.TritonError{}`.  Chase relocating `compute.TritonError` into `client.TritonError` which is the leaf in the package import graph.
The incorrect error type was discovered while using the Terraform Triton provider.
Discussed with: @cheapRoc and @stack72

Use proper error types in client.DecodeError{}

---

examples/network/create_fabric.go
network/fabrics.go
network/firewall.go

Patch a bug that was found downstream by terraform-providers/terraform-provider-triton#28. Simply missing `omitempty` in a few cases. I'll push the Terraform vendor PR as well.

Missing omitempty when creating a fabric network or firewall rule

---

storage/snaplink.go

When making a snaplink via triton-go, the presence of:
```
headers.Set("Content-Type", "application/json; type=link")
```
was causing the snaplink to fail with the error:
```
{
"code": "SourceObjectNotFound",
"message": "/stor/stack72-test3/assets.zip was not found"
}
```
By examining the manta cli tools, I was able to find that the cli doesn't need the presence of a Content-Type header. Therefore, removing the Content-Type header, and we get the correct behaviour - which in this case is a 204 response

Fix Snaplink Headers

---

README.md
examples/account/account_info.go
examples/account/config.go
examples/account/keys.go
examples/compute/create_instance.go
examples/compute/instances.go
examples/network/create_fabric.go
examples/storage/createjob.go
examples/storage/getobject.go
examples/storage/mls.go
examples/storage/putobject.go
examples/storage/signUrl.go

This supports the 3 keys ways:
* SSH Agent signer
* Passing a path to an SSH Key
* Passing the contents of an SSH KEy

Unify the way we tell people how to initialize client configuration

---

compute/instances.go

As reported in company chat, when wifi failed during a delete response, a panic was received:
```
panic: runtime error: invalid memory address or nil pointer dereference
2017-10-17T08:40:01.520-0700 [DEBUG] plugin.terraform-provider-triton_v0.2.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x15ba596]
2017-10-17T08:40:01.520-0700 [DEBUG] plugin.terraform-provider-triton_v0.2.0_x4:
2017-10-17T08:40:01.520-0700 [DEBUG] plugin.terraform-provider-triton_v0.2.0_x4: goroutine 54 [running]:
2017-10-17T08:40:01.520-0700 [DEBUG] plugin.terraform-provider-triton_v0.2.0_x4: github.com/terraform-providers/terraform-provider-triton/vendor/github.com/joyent/triton-go/compute.(*InstancesClient).Delete(0xc420063988, 0x1b90160, 0xc420014060, 0xc42003f990, 0x0, 0x0) …
```

Guard against panic when Delete request fails

---

CHANGELOG.md
compute/errors.go
compute/ping.go
compute/ping_test.go
testutils/mock_http.go

This commit is part 2 of 2 for my push to introduce unit testing. It made sense to create the HTTP mock along with the new Ping endpoint functionality since it was a basic feature. The HTTP mock and setup in this PR will work across all other endpoints with minimal effort.
This PR is missing `authentication.NewTestSigner()` which is coming in a subsequent PR after this.

Support CloudAPI's Ping endpoint

---

network/firewall.go

This wasn't as per the documentation https://apidocs.joyent.com/cloudapi/#ListMachineFirewallRules
@cheapRoc FYI ;)

Fix endpoint for compute.ListMachineRules

---

identity/client.go
identity/users.go
identity/users_test.go
testutils/mock_http.go

This adds all of the Users endpoints except `ChangePassword` right now
@cheapRoc thoughts on this please? I wasn't sure how to test this easily as it actually creates and deletes accounts

Add ability to manage users via triton-go

---

client/client.go

The new defaults are:
1) Allow HTTP KeepAlives
2) 15sec idle timeout per connection
3) 2x connections per host
4) Default max of 10x connections total for the HTTP client
The idle timeout could be made more aggressive if necessary (e.g. 5s)
but 15s seems like a reasonable default.

Enable HTTP Keepalives for the Triton client.

---

storage/directory.go
storage/objects.go

Use of `fmt.Sprintf()` was bothering my sense of aesthetics.  This should be faster and a tad more reliable.
Also fixed up some comments while here.

Use path.Join() and path.Clean() when constructing object paths.

---

client/client.go
storage/objects.go

When `triton-go` used a retriable HTTP client, it was required to use an `io.ReadSeaker`.  Now that `triton-go` doesn't use retriablehttp, relax this requirement to be just an `io.Reader`.  In the future we may revisit this and re-introduce a retriable client and promote this to an `io.ReadSeaker`, or figure out another way of passing in a Seaker.  The reason for wanting to do this is now you can read from a pipe (i.e. stdin).
This change is forward compatible.  Going back to an `io.ReadSeaker` will be backwards incompatible for people using non-seakable readers and will require additional thought.
Changelog entry: required

Move readers from an `io.ReadSeaker` to an `io.Reader`.

---

examples/storage/getobject.go
storage/objects.go

This introduces two functions under the storage package, Objects.GetInfo and a convenience wrapper called Objects.IsDir. Objects.GetInfo performs the same action as Objects.Get except that it uses the http.MethodHead type request. All headers are returned akin to GetObjectOutput except for the response body. Objects.IsDir returns either a boolean, whether or not the object is a directory, and an error in case the Objects.GetInfo call failed.
Fixes #74

storage: Introduce Objects.GetInfo for sending HEAD requests at Manta

---

examples/storage/forcePut.go
storage/objects.go

Fixes #61
when we want to Put an object in /stor/foo/bar and foo/bar doesn't exist, we will now create that object structure
```
% ./forcePut
2017/12/15 17:04:44 Folder Path "/stor/folder1/folder2/folder3/" not found
2017/12/15 17:04:44 Forcing the Creation of the Directory Tree: "/stor/folder1/folder2/folder3/foo.txt"
Successfully uploaded /tmp/foo.txt to /stor/folder1/folder2/folder3/foo.txt
```

Add support for recursively creating child directories

---

examples/storage/forcePut.go
storage/directory.go
storage/objects.go

The API allows for ambiguous input. Pass around absolute paths everywhere after crossing through the exported API.

Clean up the handling of directory sanitization. Use abs paths everywhere

---

compute/instances.go

When a network connection dropped on a GET request for an instance, a panic was thrown as follows:
```
panic: runtime error: invalid memory address or nil pointer dereference
2017-12-22T15:28:53.217+0200 [DEBUG] plugin.terraform-provider-triton_v0.3.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x15b7f95]
2017-12-22T15:28:53.217+0200 [DEBUG] plugin.terraform-provider-triton_v0.3.0_x4:
2017-12-22T15:28:53.217+0200 [DEBUG] plugin.terraform-provider-triton_v0.3.0_x4: goroutine 89 [running]:
2017-12-22T15:28:53.217+0200 [DEBUG] plugin.terraform-provider-triton_v0.3.0_x4: github.com/terraform-providers/terraform-provider-triton/vendor/github.com/joyent/triton-go/compute.(*InstancesClient).Get(0xc4202959b8, 0x1b94160, 0xc4200160c0, 0xc4202ac9c0, 0x0, 0x0, 0x0) …
```

resource/machine: Prevent panic when no network connection

---

identity/client.go
identity/policies.go
identity/policies_test.go
identity/roles.go
identity/roles_test.go
identity/users.go
identity/users_test.go

```
% [add-support-for-policies] % go test -v
=== RUN   TestListPolicies
=== RUN   TestListPolicies/successful
=== RUN   TestListPolicies/eof
=== RUN   TestListPolicies/bad_decode
=== RUN   TestListPolicies/error
--- PASS: TestListPolicies (0.00s)
--- PASS: TestListPolicies/successful (0.00s)
--- PASS: TestListPolicies/eof (0.00s)
--- PASS: TestListPolicies/bad_decode (0.00s)
--- PASS: TestListPolicies/error (0.00s)
=== RUN   TestGetPolicy
=== RUN   TestGetPolicy/successful
=== RUN   TestGetPolicy/eof
=== RUN   TestGetPolicy/bad_decode
=== RUN   TestGetPolicy/error
--- PASS: TestGetPolicy (0.00s)
--- PASS: TestGetPolicy/successful (0.00s)
--- PASS: TestGetPolicy/eof (0.00s)
--- PASS: TestGetPolicy/bad_decode (0.00s)
--- PASS: TestGetPolicy/error (0.00s)
=== RUN   TestDeletePolicy
=== RUN …
```

identity/policies: Add support for managing policies in Triton

---

.gitignore
GNUmakefile
scripts/go-test-with-coverage.sh

Gives an output as follows:
```
==> Running unit test with coverage
?       github.com/joyent/triton-go    [no test files]
ok      github.com/joyent/triton-go/account    0.015s    coverage: 90.9% of statements
?       github.com/joyent/triton-go/authentication    [no test files]
ok      github.com/joyent/triton-go/client    0.012s    coverage: 13.2% of statements
ok      github.com/joyent/triton-go/compute    0.014s    coverage: 9.9% of statements
ok      github.com/joyent/triton-go/identity    0.014s    coverage: 92.0% of statements
ok      github.com/joyent/triton-go/network    0.015s    coverage: 94.5% of statements
ok      github.com/joyent/triton-go/storage    0.013s    coverage: 3.8% of statements
```

Adding Code Coverage to GNUMakefile

---

compute/packages.go
compute/packages_test.go

This fixes an issue where we can't filter packages through CloudAPI itself. We weren't using query parameters where we should be.
~~This is still in play, I need to change the tests and add an acceptance test so we identify similar issues in the future.~~

Use proper query parameters to fix listing packages

---

version.go

This commit changes comments for some of the exported variables and functions to
make them more idiomatic, and also adds comments where such were missing.
Also, remove the else statement from the `UserAgent()` function which is not
needed given that this function returns values immediately without doing
anything else.

Refactor current comments to make them mode idiomatic.

---

identity/users.go
identity/users_test.go

This commit adds support for the ChangeUserPassword call available in the
CloudAPI, which allows for password to be updated for any valid Trition user.

Add support for the ChangeUserPassword call available in the CloudAPI.

---

account/client.go
client/client.go
compute/client.go
compute/client_test.go
compute/datacenters_test.go
compute/images_test.go
compute/instances_test.go
compute/packages_test.go
compute/ping_test.go
compute/services_test.go
compute/snapshots_test.go
compute/volumes_test.go
identity/client.go
network/client.go
storage/client.go

Ref: #124 
This is required to override HTTP signature authentication with "manual" values.
Also, rename `MockIdentityClient()` => `MockComputeClient()` within the `compute` package.

Override HTTP headers prior to backend API call

---

client/client.go
testutils/runner.go
triton.go
triton_test.go

Something I noticed while working on `triton-go` lately is that we should probably rename `client.GetTritonEnv` => `triton.GetEnv`. This will help maintain our environment variable configuration at the root of the project for easier consumption. I've also added a unit test.

root: Move GetTritonEnv into root triton package

---

compute/instances.go

This commit adds missing call to the `Close()` method for the underlying
`io.ReadCloser` interface, which an cause a potential memory leak.

compute/instances: Add missing Close() for the response body.

---

authentication/agent_key_identifier.go
authentication/private_key_signer.go
authentication/signer.go
authentication/ssh_agent_signer.go
authentication/test_signer.go
client/client.go

The RBAC HTTP Signatures between manta and triton are slightly different
Therefore, we need to generate the signature based on whether the request
is for RBAC AND for Manta or not
We therefore, moved the logic to a central generate func rather than being
handled different;y between private key and ssh agent signers
Paired on this with @cheapRoc

Manta RBAC authentication support.

---

identity/roles.go
identity/roles_test.go

This commit adds support for the SetRoleTags call available in the
CloudAPI, which allows for setting a single or multiple role tags
to use with the RBAC, either for an individual resource or for the
whole group of resources (e.g., all the current instances, etc.).
Additionally, this commit also adds GetRoleTags function, whilst not
provided by the CloudAPI, can be used to retrieve a list of currently
set role tags.

Add support for the SetRoleTags call available in the CloudAPI.

---

client/client.go
compute/client_test.go

Small change needed to fix an issue with TSG submitting requests to CloudAPI. `Header.Add` was creating duplicate and empty headers which CloudAPI (justifiably) denies. Since the name of the method is `override` header (and this is a hack to get some functionality working anyway) I'm ok with changing it to `Header.Set`.

client: overrideHeader needs to use Header.Set not Header.Add

---

account/account.go
account/account_test.go
cmd/agent/account/public.go
cmd/config/config.go
cmd/internal/config/public.go
cmd/triton/cmd/account/get/public.go
cmd/triton/cmd/account/public.go
cmd/triton/cmd/account/update/public.go
cmd/triton/cmd/instances/list/public.go
cmd/triton/cmd/root.go

This adds GET and UPDATE for triton account command
This PR also needs to change the Account Update request to use a
POST rather than a PUT as per the API documentation. Without this,
it doesn't actually make the changes in the API

cli/account: Add the ability to manage Triton account from CLI

---

compute/instances.go

I tested this with the following 4 scenarios and it appeared to work fine.
1) Provided Both NetworkObject and Network.
2) Providing only a Network.
3) Providing a NetworkObject with only a IPv4UUID.
4) Providing a NetworkObject with a IPv4UUI and IPv4IPs.
```
nic, err := c.Instances().AddNIC(context.Background(), &compute.AddNICInput{
InstanceID: "8358344e-299a-4fda-bc3b-d4b4c2787bde",
NetworkObject: compute.NetworkObject{
IPv4UUID: "0a63f067-d721-435e-941a-724776d69c91",
IPv4IPs:  []string{"10.1.1.58"},
},
Network: "71a1abac-f003-4b51-ac63-28d37f2ef0af",
})
```

added networkobject support to ADDNic

---

authentication/dummy.go

👋Hello!
This PR introduces a build tag to exclude the dummy credentials from being included in built binaries using this package.
```console
$ file before
before: Mach-O 64-bit executable x86_64  
$ strings before | grep "RSA PRIVATE"
-----BEGIN RSA PRIVATE KEY-----
-----END RSA PRIVATE KEY-----
```
```console
$ file after
after: Mach-O 64-bit executable x86_64
$ strings after | grep "RSA PRIVATE"
```

Add build tag to ignore dummy.go from builds

---

CHANGELOG.md
compute/images_test.go
version.go

Fix panic when testing images without TRITON_TEST set
```
--- FAIL: TestAccImagesListInput (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13016c6]
goroutine 32 [running]:
testing.tRunner.func1.1(0x1383a80, 0x16c79a0)
/usr/local/go/src/testing/testing.go:940 +0x2f5
testing.tRunner.func1(0xc000147e60)
/usr/local/go/src/testing/testing.go:943 +0x3f9
panic(0x1383a80, 0x16c79a0)
/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/joyent/triton-go/v2/compute_test.TestAccImagesListInput(0xc000147e60)
/Users/pedropc/work/triton-go/compute/images_test.go:130 +0xd6
testing.tRunner(0xc000147e60, 0x14093e8) …
```

Fix panic when testing images without TRITON_TEST set

---

cmd/triton/cmd/instances/public.go
cmd/triton/cmd/root_test.go

The following error happens when you try to get an instance by id using the command line triton wrapper:
```
cmd/triton/triton instance get --id be94b42b
Error: unknown flag: --id
2020-05-14T19:48:30.445428000+02:00 |ERRO| unable to run error="unknown flag: --id"
```

Fix command `cmd/triton/triton instance get --id`

---

CHANGELOG.md
account/accesskeys.go
account/accesskeys_test.go
account/client.go

Tests passing so far:
```
triton-go(TRITON-2152) pedropc$ go test -v ./account/accesskeys_test.go
=== RUN   TestAccAccessKey_Create
[DEBUG] Created access key &{AccessKeyID:f3e8c7d987e333d8d84d8868c66dac2d SecretAccessKey:6f397999e5747d4fa0f817a02352e2cb9d517cd15a63caea70358fbd076c1e4b CreateDate:2020-07-30 15:39:34.029 +0000 UTC Status:Active UserName:account}
--- PASS: TestAccAccessKey_Create (0.37s)
=== RUN   TestAccAccessKey_GetAndList
[DEBUG] Created access key &{AccessKeyID:43d5da8698a86857b7f9783832985066 SecretAccessKey:76e719310ad1ce9beeb503349c2ef92f98711f064d980b2e65e59a8b078229a9 CreateDate:2020-07-30 15:39:34.378 +0000 UTC Status:Active UserName:account}
--- PASS: TestAccAccessKey_GetAndList (0.42s)
=== RUN   TestAccAccessKey_Delete
[DEBUG] Created access key …
```

TRITON-2152 Add support for AccessKeys

---

CHANGELOG.md
cmd/agent/account/public.go
cmd/config/config.go
cmd/internal/config/public.go
cmd/triton/cmd/accesskeys/create/public.go
cmd/triton/cmd/accesskeys/delete/public.go
cmd/triton/cmd/accesskeys/get/public.go
cmd/triton/cmd/accesskeys/list/public.go
cmd/triton/cmd/accesskeys/public.go
cmd/triton/cmd/root.go
version.go

```
thanagar: triton-go(master) pedropc$ ./cmd/triton/triton accesskeys list
ID  SECRET
thanagar: triton-go(master) pedropc$ ./cmd/triton/triton accesskeys create
Created access key "9bca5e6ff274bb367eda605c863c3893"
thanagar: triton-go(master) pedropc$ ./cmd/triton/triton accesskeys list
ID                                              SECRET
9bca5e6ff274bb367eda605c863c3893  b34a740fec8115f3b1e47a4a0b0f740c38f32d9821dba7d21d18b46663fb1f2a
thanagar: triton-go(master) pedropc$ ./cmd/triton/triton accesskeys get --accesskeyid 9bca5e6ff274bb367eda605c863c3893
b34a740fec8115f3b1e47a4a0b0f740c38f32d9821dba7d21d18b46663fb1f2a
thanagar: triton-go(master) pedropc$ ./cmd/triton/triton accesskeys delete --accesskeyid 9bca5e6ff274bb367eda605c863c3893
Deleted access key …
```

TRITON-2152 Added `triton accesskeys create|get|list|delete` subcommands
